# Generated by Django 5.2.8 on 2025-12-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('History', 'History'), ('Biography', 'Biography'), ('Science', 'Science'), ('Technology', 'Technology'), ('Programming', 'Programming'), ('Business', 'Business'), ('Education', 'Education'), ('Philosophy', 'Philosophy'), ('Literature', 'Literature'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the book', null=True),
        ),
    ]
